# Generated by Django 3.0.7 on 2020-06-12 10:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titleRf', models.CharField(max_length=250)),
                ('descriptionRf', models.TextField()),
                ('linkRf', models.URLField()),
                ('createdRf', models.DateTimeField(auto_now_add=True)),
                ('updatedRf', models.DateTimeField(auto_now=True)),
                ('authorRf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reference_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-titleRf',),
            },
        ),
    ]
