# Generated by Django 3.0.7 on 2020-06-12 12:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('references', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-statusRf',)},
        ),
        migrations.AddField(
            model_name='post',
            name='statusRf',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10),
        ),
        migrations.AlterField(
            model_name='post',
            name='authorRf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
